databases:
  - name: psyko-mode-db
    plan: free

services:
  - type: web
    name: psyko-mode
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psyko-mode-db
          property: connectionString
